# Generated by Django 5.0.2 on 2025-10-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workos_id',
            field=models.CharField(blank=True, db_index=True, help_text='WorkOS user ID for SSO authentication', max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['workos_id'], name='users_workos__d44c7f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['points'], name='users_points_1473cb_idx'),
        ),
    ]
