# Generated by Django 5.0.2 on 2025-10-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_user_workos_id_user_users_email_4b85f2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='previous_rank',
            field=models.IntegerField(default=0, help_text='Last known leaderboard rank for change detection'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_badge_earned',
            field=models.BooleanField(default=True, help_text='Receive SMS when you earn a new badge', verbose_name='Badge earned notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_daily_challenge',
            field=models.BooleanField(default=False, help_text='Receive SMS about new daily challenges (opt-in)', verbose_name='Daily challenge notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_entry_verified',
            field=models.BooleanField(default=True, help_text='Receive SMS when someone verifies your entry', verbose_name='Entry verified notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_leaderboard',
            field=models.BooleanField(default=False, help_text='Receive SMS when your leaderboard rank changes significantly', verbose_name='Leaderboard change notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_level_up',
            field=models.BooleanField(default=True, help_text='Receive SMS when you advance to a new level', verbose_name='Level up notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_needs_revision',
            field=models.BooleanField(default=True, help_text='Receive SMS when your entry needs revision', verbose_name='Entry revision notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_streak_milestone',
            field=models.BooleanField(default=True, help_text='Receive SMS at streak milestones (3, 7, 14, 30+ days)', verbose_name='Streak milestone notifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for SMS notifications (format: +231770123456)', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='users_phone_n_a3b1c5_idx'),
        ),
    ]
