# Generated by Django 5.0.2 on 2025-09-21 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Word Categories',
                'db_table': 'word_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KoloquaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koloqua_text', models.CharField(db_index=True, max_length=255)),
                ('english_translation', models.TextField()),
                ('literal_translation', models.TextField(blank=True, help_text='Word-for-word translation if different from meaning')),
                ('entry_type', models.CharField(choices=[('word', 'Word'), ('phrase', 'Phrase'), ('idiom', 'Idiom'), ('proverb', 'Proverb')], default='word', max_length=20)),
                ('context_explanation', models.TextField(help_text='Explain when and how this is used')),
                ('example_sentence_koloqua', models.TextField()),
                ('example_sentence_english', models.TextField()),
                ('cultural_notes', models.TextField(blank=True, help_text='Any cultural context or significance')),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags for easier searching')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], default='pending', max_length=20)),
                ('verification_count', models.IntegerField(default=0)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('pronunciation_guide', models.CharField(blank=True, max_length=255)),
                ('audio_pronunciation', models.FileField(blank=True, null=True, upload_to='pronunciations/')),
                ('region_specific', models.CharField(blank=True, help_text='Specific region where this is used', max_length=100)),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='entries', to='dictionary.wordcategory')),
            ],
            options={
                'verbose_name': 'Koloqua Entry',
                'verbose_name_plural': 'Koloqua Entries',
                'db_table': 'koloqua_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(max_length=255)),
                ('search_language', models.CharField(choices=[('en', 'English'), ('ko', 'Koloqua')], max_length=10)),
                ('found', models.BooleanField(default=False)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('result_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.koloquaentry')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Translation Histories',
                'db_table': 'translation_history',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='EntryVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='dictionary.koloquaentry')),
            ],
            options={
                'db_table': 'entry_votes',
                'unique_together': {('entry', 'voter')},
            },
        ),
        migrations.CreateModel(
            name='EntryVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('accurate', 'Accurate'), ('needs_revision', 'Needs Revision'), ('incorrect', 'Incorrect')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='dictionary.koloquaentry')),
            ],
            options={
                'db_table': 'entry_verifications',
                'ordering': ['-created_at'],
                'unique_together': {('entry', 'verifier')},
            },
        ),
        migrations.AddIndex(
            model_name='koloquaentry',
            index=models.Index(fields=['koloqua_text', 'status'], name='koloqua_ent_koloqua_f7f049_idx'),
        ),
        migrations.AddIndex(
            model_name='koloquaentry',
            index=models.Index(fields=['status', 'created_at'], name='koloqua_ent_status_ee4855_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='koloquaentry',
            unique_together={('koloqua_text', 'contributor')},
        ),
    ]
