# Generated by Django 5.0.2 on 2025-09-22 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstreak',
            name='accepted_challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamification.dailychallenge'),
        ),
        migrations.AddField(
            model_name='userstreak',
            name='accepted_challenge_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
