# Generated by Django 5.0.2 on 2025-09-24 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_userstreak_accepted_challenge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userstreak',
            name='completed_challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_by', to='gamification.dailychallenge'),
        ),
        migrations.AddField(
            model_name='userstreak',
            name='completed_challenge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('contribution', 'New Contribution'), ('verification', 'Verification'), ('vote', 'Vote Cast'), ('vote_received', 'Vote Received'), ('vote_changed', 'Vote Changed'), ('vote_removed', 'Vote Removed'), ('daily_bonus', 'Daily Bonus'), ('achievement', 'Achievement'), ('penalty', 'Penalty')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userstreak',
            name='accepted_challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_by', to='gamification.dailychallenge'),
        ),
    ]
