# Generated by Django 5.0.2 on 2025-10-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_userstreak_completed_challenge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('contribution', 'New Contribution'), ('verification', 'Verification'), ('vote', 'Vote Cast'), ('vote_received', 'Vote Received'), ('vote_changed', 'Vote Changed'), ('vote_removed', 'Vote Removed'), ('daily_bonus', 'Daily Bonus'), ('achievement', 'Achievement'), ('penalty', 'Penalty')], max_length=50),
        ),
    ]
